language: minimal
sudo: required
dist: trusty
git:
  submodules: false
cache:
  directories:
  - "$HOME/.mafia"
  - "$HOME/.cabal"
matrix:
  include:
  - env: GHCVER=8.2.2 CABALVER=2.0
    addons:
      apt:
        update: true
        sources:
          - hvr-ghc
        packages:
          - ghc-8.2.2
          - cabal-install-2.0
  #allow-failures:
  #  - env: GHCVER=head
addons:
  apt:
    update: true
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2
      - libgmp-dev

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
  # time it out before travis kills it.
  # If travis times out the build, it wont save the cache, meaning the
  # next build will also most likely timeout
  # (travis_wait doesnt work btw, theres still a global timeout of
  # approx 40 mins it seems.
  - timeout 35m bin/ci
